DROP TABLE IF EXISTS DemoFW;

CREATE TABLE DemoFW(
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(10) NOT NULL,
    first_name VARCHAR(10) NOT NULL,
    email VARCHAR(40) NOT NULL,
    PRIMARY KEY (id)
)